export const DUMMY_POPULAR_DICTIONARY = [
    {
        id: 1,
        index: 1,
        keyword: "chmod",
        tag: "COMMAND",
        description: "파일이나 디렉터리의 접근 권한을 변경, 파일이나 디렉터리의 접근 권한을 변경aslkdfj",
    },
    {
        id: 2,
        index: 2,
        keyword: "find",
        tag: "COMMAND",
        description: "파일 또는 디렉터리를 조건에 맞게 검색",
    },
    {
        id: 3,
        index: 3,
        keyword: "grep",
        tag: "CONCEPT",
        description: "파일이나 입력 내용에서 특정 문자열을 검색",
    },
    {
        id: 4,
        index: 4,
        keyword: "ls",
        tag: "FILE",
        description: "디렉터리의 파일 및 디렉터리 목록을 출력",
    },
    {
        id: 5,
        index: 5,
        keyword: "cd",
        tag: "CONCEPT",
        description: "현재 작업 디렉터리를 변경",
    },
    {
        id: 6,
        index: 6,
        keyword: "mkdir",
        tag: "FILE",
        description: "새로운 디렉터리를 생성",
    },
    {
        id: 7,
        index: 7,
        keyword: "ps",
        tag: "CONCEPT",
        description: "현재 실행 중인 프로세스 정보를 출력",
    },
    {
        id: 8,
        index: 8,
        keyword: "kill",
        tag: "FILE",
        description: "프로세스에 시그널을 전송",
    },
];

export const DUMMY_RECENT_DICTIONARY = [
    {
        id: 1,
        keyword: "chmod",
        tag: "COMMAND",
        description: "파일이나 디렉터리의 접근 권한을 변경",
        time: "1분 전",
    },
    {
        id: 2,
        keyword: "find",
        tag: "COMMAND",
        description: "파일 또는 디렉터리를 조건에 맞게 검색",
        time: "23분 전",
    },
    {
        id: 3,
        keyword: "grep",
        tag: "COMMAND",
        description: "파일이나 입력 내용에서 특정 문자열을 검색",
        time: "5시간 전",
    },
    {
        id: 4,
        keyword: "passwd",
        tag: "FILE",
        description: "사용자 계정과 관련된 정보를 저장하는 파일",
        time: "23시간 전",
    },
    {
        id: 5,
        keyword: "process",
        tag: "CONCEPT",
        description: "현재 실행 중인 프로그램의 인스턴스",
        time: "어제",
    },
];

export const DUMMY_COMMUNITY = [
    {
        id: 1,
        tag: "notice",
        description: "리눅스마스터 시험 관련 문항 100개 추가 안내",
    },
    {
        id: 2,
        tag: "notice",
        description: "터미널 실습 환경 개선",
    },
    {
        id: 3,
        tag: "notice",
        description: "인증 가능한 자격증 추가 안내",
    },
    {
        id: 4,
        tag: "qna",
        description: "chmod 권한 설정 관련 질문",
    },
    {
        id: 5,
        tag: "free",
        description: "Linux Lab 사용 후기",
    },
];

export const DUMMY_DICTIONARY = [
    {
        id: 1,
        type: "CONCEPT",
        title: "파일 권한",
        description: "Linux 파일과 디렉터리에 적용되는 읽기, 쓰기, 실행 권한을 설명한다.",
        tags: ["파일", "권한", "보안"],
    },
    {
        id: 2,
        type: "CONCEPT",
        title: "심볼릭 링크",
        description: "다른 파일이나 디렉터리를 참조하는 특수한 형태의 파일을 설명한다.",
        tags: ["파일", "링크", "파일시스템"],
    },
    {
        id: 3,
        type: "COMMAND",
        title: "cd",
        description: "현재 작업 디렉터리를 다른 디렉터리로 변경한다.",
        tags: ["디렉터리", "경로", "이동"],
    },
    {
        id: 4,
        type: "COMMAND",
        title: "find",
        description: "지정한 조건에 따라 파일과 디렉터리를 검색한다.",
        tags: ["파일", "검색", "탐색"],
    },
    {
        id: 5,
        type: "COMMAND",
        title: "grep",
        description: "파일이나 표준 입력에서 특정 패턴과 일치하는 문자열을 검색한다.",
        tags: ["텍스트", "검색", "필터"],
    },
    {
        id: 6,
        type: "CONCEPT",
        title: "프로세스",
        description: "Linux 시스템에서 실행 중인 프로그램의 인스턴스를 설명한다.",
        tags: ["프로세스", "시스템", "실행"],
    },
    {
        id: 7,
        type: "COMMAND",
        title: "kill",
        description: "프로세스에 지정한 시그널을 전달한다.",
        tags: ["프로세스", "시그널", "종료"],
    },
    {
        id: 8,
        type: "FILE",
        title: "/etc/passwd",
        description: "시스템 사용자 계정의 기본 정보를 저장하는 파일이다.",
        tags: ["사용자", "계정", "설정파일"],
    },
    {
        id: 9,
        type: "FILE",
        title: "/etc/group",
        description: "시스템에 등록된 그룹 정보를 저장하는 파일이다.",
        tags: ["사용자", "그룹", "설정파일"],
    },
    {
        id: 10,
        type: "COMMAND",
        title: "ip",
        description: "네트워크 인터페이스, 주소, 라우팅 등의 정보를 조회하고 설정한다.",
        tags: ["네트워크", "인터페이스", "설정"],
    },
    {
        id: 11,
        type: "COMMAND",
        title: "ssh",
        description: "SSH 프로토콜을 이용해 원격 시스템에 안전하게 접속한다.",
        tags: ["네트워크", "SSH", "원격"],
    },
    {
        id: 12,
        type: "COMMAND",
        title: "tar",
        description: "여러 파일과 디렉터리를 하나의 아카이브 파일로 묶거나 해제한다.",
        tags: ["파일", "아카이브", "압축"],
    },
    {
        id: 13,
        type: "CONCEPT",
        title: "데몬",
        description: "백그라운드에서 지속적으로 실행되며 특정 작업을 수행하는 프로세스를 설명한다.",
        tags: ["시스템", "서비스", "프로세스"],
    },
    {
        id: 14,
        type: "FILE",
        title: "/etc/fstab",
        description: "시스템에서 사용할 파일 시스템과 마운트 정보를 정의하는 설정 파일이다.",
        tags: ["파일시스템", "마운트", "설정파일"],
    },
    {
        id: 15,
        type: "FILE",
        title: "/etc/hosts",
        description: "호스트 이름과 IP 주소의 정적 매핑 정보를 저장하는 파일이다.",
        tags: ["네트워크", "호스트", "설정파일"],
    },
    {
        id: 16,
        type: "CONCEPT",
        title: "마운트",
        description: "파일 시스템을 특정 디렉터리에 연결하여 접근할 수 있게 하는 개념이다.",
        tags: ["파일시스템", "마운트", "스토리지"],
    },
];